### ISSUE TITLE
Explorer link in docs is broken

### ISSUE THREAD

**Issue by IvanRF** [fuseio/docs#13]
Explorer link on https://docs.fuse.io/ top menu points to https://explorer.fusenet.io/

Maybe it was missed on https://github.com/fuseio/docs/pull/1 😃

**Comment by Marksmargon** [comment]
Thanks for the comment - that is fixed

**Comment by IvanRF** [comment]
@leonprou The link still points to https://explorer.fusenet.io/ which throws the error `502 Bad Gateway`.

Change it to https://explorer.fuse.io/

**Comment by Marksmargon** [comment]
Fixed - thanks!
