### ISSUE TITLE
User Experience: Include wallet address in writing below QR Code.

### ISSUE THREAD

**Issue by kaiofabian** [fuseio/docs#16]
When I click on Receive this modal appears with QR CODE. It remains to inform the address number in writing.

![WhatsApp Image 2021-08-02 at 19 30 20](https://user-images.githubusercontent.com/23060780/127931817-3d808685-9d8c-4348-bcde-199e1401a7c5.jpeg)

Donations: 0x8498aB1e3106eFa5884A8A3D4d7Cf66EE3c4b895

**Comment by kaiofabian** [comment]
I tried to locate my Fuse coin wallet number. I clicked the "Account" button and then clicked the "Receive" button. This button is for receiving coins in the wallet, right? If so, just open a QRCODE and I needed to copy the wallet address without needing to scan the QRCODE. So, as I'm testing my own user experience, I missed the address on the screen with the option to "copy" the numbering, along with the QRCODE.

That way, users can copy or scan the address.

**Comment by kaiofabian** [comment]
![WhatsApp Image 2021-08-04 at 10 20 57](https://user-images.githubusercontent.com/23060780/128189759-7dcb6676-0952-437b-9629-c38c366d1846.jpeg)

Despite being so simple, this is a usability issue, as the receive button is next to the wallet's QR code on separate buttons. Novice or lay users may be confused or not understand that this number is the code to receive coins in your wallet.

**Comment by MikeNek** [comment]
Hey @kaiofabian. Thanks for this comment.
In fact, we are currently working on updating the design of the application, and we want to change the location and behaviour of these buttons.
Thank you very much for your point of view, it confirms that we were right when decided to change this!

**Comment by kaiofabian** [comment]
Perfect. Happy to be able to help in any way.
