### ISSUE TITLE
Link broken - Adding Liquidity 

### ISSUE THREAD

**Issue by kaiofabian** [fuseio/docs#19]
Hello,
I was reading the documentation (https://docs.fuse.io/fuseswap/adding-liquidity) and noticed an incorrect link that goes to http://www.explorer.fuse.io/ and the correct one is http://explorer.fuse.io

The error is found in the paragraph that says:
"Once the transaction is confirmed on-chain click on "Supply" and approve the transaction. You will receive the liquidity pool tokens on your wallet which can be checked under tokens through www.explorer.fuse.io on your wallet address."
![Captura de tela_2021-08-11_14-40-07](https://user-images.githubusercontent.com/23060780/129077298-ac32af6a-9db0-43a5-9949-32ad732c60ee.png)

Donations: 0x8498aB1e3106eFa5884A8A3D4d7Cf66EE3c4b895

**Comment by Marksmargon** [comment]
Can you fix please @ashfuse ?

**Comment by ashfuse** [comment]
I have fixed it. @Marksmargon @kaiofabian . Thank you for letting me know.
